import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Page from "../layout/page";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Spotify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`text-neutral-100 overflow-hidden h-screen ${inter.className}`}>
        <Page>{children}</Page>
      </body>
    </html>
  );
}
