import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/common/sidebar";
import Footer from "../components/common/footer";
import Navbar from "../components/common/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col w-full h-screen bg-neutral-950 text-neutral-100 ">
          <div className="flex flex-1  w-full gap-2">
            <Sidebar />
            <div className="flex flex-col w-full">
              <Navbar />
              {children}
            </div>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
